language: java
sudo: required
dist: trusty
group: edge
jdk:
  - oraclejdk8
  - oraclejdk9
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/b37a582210ebff5dde7c
    on_success: change
    on_failure: always
    on_start: never
